version: '2'
services:
  web:
    build: 
      context : .
      dockerfile: Dockerfiles/plusbase.Dockerfile
    ports:
      - "80"
      - "443"
    volumes:
      - ./log:/var/nginx/log
      - ./www/bootstrap:/var/www