version: '2'
services:
  web:
    build: 
      context: ./Dockerfiles
      dockerfile: plusbase.DockerFile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./log:/var/nginx/log
      - ./www/bootstrap:/var/www